[config]
schemaVersion = "0.0.1"

[general]
repository = "https://thunderstore.io"

[package]
namespace = "www_Day_Dream"
name = "Instance_Method_Injector"
description = "A preload patcher that injects *blank* Unity Event methods, or really any method name, onto mod-requested objects for use with typical MonoMod patching."
websiteUrl = "https://github.com/www-Day-Dream/Daydream.InstanceMethodInjector"
containsNsfwContent = false

[package.dependencies]
BepInEx-BepInExPack = "5.4.2100"

[build]
icon = "./icon.png"
readme = "../README.md"
outdir = "../dist/"

[[build.copy]]
source  = "../Daydream.InstanceMethodInjector/bin/Release/Daydream.InstanceMethodInjector.dll"
target = "/BepInEx/patchers/Daydream.InstanceMethodInjector.dll"

[[build.copy]]
source = "../LICENSE.txt"
target = "LICENSE.txt"


[publish]
communities = ["lethal-company"]

[publish.categories]
lethal-company = ["bepinex", "libraries", "tools"]